### ISSUE TITLE
Adding velocity fields from different netcdf files (different grids and  time vectors)

### ISSUE THREAD

**Issue by slawchune** [OceanParcels/parcels#547] opened 2019-02-27 16:47 UTC
Hello Eric and Phillipe, 

I encouter an issue when I want to add two velocity fields from different data.

I tried to use the example given in the "Summed Fields" tutorial, but it fails for my case.  In one word, I want to add a current field and a wind drift field together for advection.  

I load separatly a "fieldset_current" and a "fieldset_wind" from netcdf files that have those grids : 

```
In [112]: fieldset_current.U.lon
Out[112]: 
array([-180.     , -179.91667, -179.83333, ...,  179.75   ,  179.83334,
        179.91666], dtype=float32)

In [113]: fieldset_current.U.lat
Out[113]: 
array([-80.      , -79.916664, -79.833336, ...,  89.833336,  89.916664,
        90.      ], dtype=float32)

In [114]: fieldset_current.U.time
Out[114]: 
array([     0.,   3600.,   7200.,  10800.,  14400.,  18000.,  21600.,
        25200.,  28800.,  32400.,  36000.,  39600.,  43200.,  46800.,
        50400.,  54000.,  57600.,  61200.,  64800.,  68400.,  72000.,
        75600.,  79200.,  82800.,  86400.,  90000.,  93600.,  97200.,
       100800., 104400., 108000., 111600., 115200., 118800., 122400.,
       126000., 129600., 133200., 136800., 140400., 144000., 147600.,
       151200., 154800., 158400., 162000., 165600., 169200., 172800.,
       176400., 180000., 183600., 187200., 190800., 194400., 198000.,
       201600., 205200., 208800., 212400., 216000., 219600., 223200.,
       226800., 230400., 234000., 237600., 241200., 244800., 248400.,
       252000., 255600., 259200., 262800., 266400., 270000., 273600.,
       277200., 280800., 284400., 288000., 291600., 295200., 298800.,
       302400., 306000., 309600., 313200., 316800., 320400., 324000.,
       327600., 331200., 334800., 338400., 342000., 345600., 349200.,
       352800., 356400., 360000., 363600., 367200., 370800., 374400.,
       378000., 381600., 385200., 388800., 392400., 396000., 399600.,
       403200., 406800., 410400., 414000., 417600., 421200., 424800.,
       428400., 432000., 435600., 439200., 442800., 446400., 450000.,
       453600., 457200., 460800., 464400., 468000., 471600., 475200.,
       478800., 482400., 486000., 489600., 493200., 496800., 500400.,
       504000., 507600., 511200., 514800.])

In [117]: fieldset_wind.U.lon
Out[117]: 
array([0.000e+00, 2.000e-01, 4.000e-01, ..., 3.594e+02, 3.596e+02,
       3.598e+02], dtype=float32)
In [120]: fieldset_wind.U.lat[0:10]
Out[120]: 
array([-90. , -89.8, -89.6, -89.4, -89.2, -89. , -88.8, -88.6, -88.4,
       -88.2], dtype=float32)
In [122]: fieldset_wind.U.time[0:10]
Out[122]: 
array([    0., 10800., 21600., 32400., 43200., 54000., 64800., 75600.,
       86400., 97200.])


```

They don't also have the same time origin : 

```

In [123]: fieldset_wind.time_origin
Out[123]: numpy.datetime64('2018-02-01T00:00:00.000000000')
In [125]: fieldset_current.time_origin
Out[125]: numpy.datetime64('2018-02-26T00:30:00.000000000')
```
fieldset_wind was also scaled with a factor :

```
        fieldset_wind.U.set_scaling_factor(wind_factor)
        fieldset_wind.V.set_scaling_factor(wind_factor)
```

What I simply tried to do, as suggested by the tutorial was : 

`fieldset = FieldSet(U=fieldset_current.U+fieldset_wind.U, V=fieldset_current.V+fieldset_wind.V)`

Now, fieldset contains two fielset, but one time origin : 

```
In [127]: fieldset.U
Out[127]: 
[<parcels.field.Field at 0x2b8fccb36668>,
 <parcels.field.Field at 0x2b8f6e483a20>]
In [129]: fieldset.time_origin
Out[129]: numpy.datetime64('2018-02-26T00:30:00.000000000')
```
But the result is not good, the particles are advected only with the wind field, and not the sum. Here attached a picture that shows this behaviour. It shows some trajectories launched from a surface drifter (black) where the green trajectories (wind only) are confounded with the orange one (wind +current). The blue trajectoires are the one obtained with the current. 

How can I achieve my goal ? 

Second question : I have chosen this time origin of the SummedField to compute my particle init 

```
    date0_field=datetime.datetime.utcfromtimestamp(fieldset.time_origin.tolist()/1e9)
    launch_time=(launch_date-date0_field).total_seconds()

    # initialise the set of particle in Parcels kernel
    pset = ParticleSet(fieldset=fieldset, pclass=JITParticle,
                       lon=launch_lon, lat=launch_lat, time=launch_time)
```
Is this correct ? 

Thanks for your help !
Stéphane 
![field_sum_parcels_issue](https://user-images.githubusercontent.com/43207640/53507115-93867700-3ab7-11e9-8c7d-ad7a86be3883.png)

**Comment by erikvansebille** [comment] 2019-02-28 13:12
Hi Stéphane,

Thanks for your question. To begin with the easy one, about your code snippet
```
    date0_field=datetime.datetime.utcfromtimestamp(fieldset.time_origin.tolist()/1e9)
    launch_time=(launch_date-date0_field).total_seconds()

    # initialise the set of particle in Parcels kernel
    pset = ParticleSet(fieldset=fieldset, pclass=JITParticle,
                       lon=launch_lon, lat=launch_lat, time=launch_time)
```
This is correct I guess, but the `time` argument in `ParticleSet` also accepts `datetime` objects, so all the conversion you're doing in the first two lines is unnecessary. That can be done by Parcels too!

The questions about the `SummedFields` is trickier to answer (and please, could you next time open separate issues, so that we keep the Issues clean and easy to refer to for others?)

It is expected that the new `fieldset` has only one time_origin, and that it is set to the time_origin of the first `U` in the summation (so `fieldset_current.U` since for you `fieldset = FieldSet(U=fieldset_current.U+fieldset_wind.U, V=fieldset_current.V+fieldset_wind.V)`). Since each `Field` still has its own `time` vector, and since these don't have to start at zero and can even be negative too, the value of `time_origin` is somewhat arbitrary.

I'm not sure why the summing doesn't seem to work, but to dig into that I would need access to your code and data. If you're happy to share that with me, can you email me with that info? I will then have a look

**Comment by slawchune** [comment] 2019-03-01 14:55
Hi Eric,

Firstly, thanks for the tip on the time conversion thing. So I guess it is more effective to always use a datetime object to initialise particles (so we avoid to have to check the fieldset time origin).

Concerning the summation of avective fields, I have tried to prepare a simple example here : 
  
https://atlas.mercator-ocean.fr/s/ScTPGtxbbaJ32YN

The code is inside the python script : test.py

Weirdly, I encounter with this example some 'out of boundary' or 'Segmentation fault (core dumped)' at some point using the wind data. I didn't have this issues previously. I assumed it came maybe from the dimension (depth wasn't present) or the longitude grid (0,360), so I tried to work around a bit the wind file with nco (the three file versiond), but witouth any success. 

Stéphane

**Comment by erikvansebille** [comment] 2019-03-04 07:01
Hi Stéphane,

I had a look at your code, and think I know what's going on. The problem is that both your  `fieldset_current` as your `fieldset_wind` have fields named `U` and `V`. This causes problems in the part of Parcels where the C-code is generated. 

Could you try whether you get better agreement when you run in Scipy mode, by using `pset = ParticleSet(fieldset=fieldset, pclass=ScipyParticle, ...)`? Running in Scipy mode will [be much slower](https://github.com/OceanParcels/parcels/blob/master/parcels/examples/tutorial_jit_vs_scipy.ipynb), but it would be good to get confirmed whether this option fixes the issue

As some background to what I think is going on: note that in the [SummedFields tutorial](https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_SummedFields.ipynb) we use different names for the `U` and the `Ustokes` Fields. Downside of that approach is that it's not easy to create a `FieldSet` of just the Stokes velocities, as a `FieldSet` always requires at least a `Field` named `U` (and `V`).

In the meantime, we'll work on a fix so that what you wanted to do: create two FieldSets that work separately, and also can easily be combined. And then hope that that fixes your problem!

**Comment by erikvansebille** [comment] 2019-03-05 06:56
Further to my message from yesterday, I think we now have a fix in #555, which I've just merged into master. @slawchune, can you check if your original code (so with `pclass=JITParticle`) works with this latest master branch?

**Comment by slawchune** [comment] 2019-03-06 14:32
OK everything is now fixed :) Thanks for the workaround Eric !

![all_trajectories](https://user-images.githubusercontent.com/43207640/53888477-e9619e80-4024-11e9-9bc7-87848a62c848.png)

**Comment by erikvansebille** [comment] 2019-03-06 14:49
Great, glad to hear that this fix worked. It's now also part of v2.0.0beta2 that was released on conda-forge yesterday. So you can use `conda update parcels` to have this fix included there too

**Closed by erikvansebille** 2019-03-06 14:49 UTC
