### ISSUE TITLE
Seafloor water current extrapolation method

### ISSUE THREAD

**Issue by miquelmassot** [OceanParcels/parcels#830] opened 2020-04-30 11:41 UTC
Most NetCDF ocean current models do not provide flow currents down to the seafloor. Sometimes they stop the measurements a couple of grid cells above the seafloor. Thus, when interpolating a current value in grid cells where its neighbours are zero, the result is zero. However, it would be interesting to provide an option to extrapolate seafloor current to the deepest available current.

For example, the following code shows a fieldset loaded with `Alt` as elevation, obtained from a GEBCO netCDF file. At a particular (lat, lon), the currents at depth cannot be obtained, as it is two grid cells below the last measurement, making any interpolation result in zero.

```python 
lat = 63.57
lon = 10.5

x = lon
y = lat
z = - fieldset.Alt[0, 0, y, x]

print('At (',lat,',',lon,') depth:',z)
u = fieldset.U[0, z, y, x]
v = fieldset.V[0, z, y, x]
print('u:', u, 'v:',v)

(_, _, _, xi, yi, zi) = fieldset.U.search_indices(x, y, z, 0, 0)
print('Indices are:',xi, yi, zi)
print('Current u:',fieldset.U.data[0, zi, yi, xi],'at depth', fieldset.U.grid.depth[zi])
print('Shallower u:',fieldset.U.data[0, zi-1, yi, xi],'at depth', fieldset.U.grid.depth[zi-1])
```

returns

``` 
At ( 63.57 , 10.5 ) depth: 250.07764651843837
u: 0.0 v: 0.0
Indices are: 14 4 26
Current u: 0.0 at depth 222.4752
Shallower u: 0.007934812 at depth 186.1256
```
would it be possible to indicate the kernel to extrapolate seafloor current to the last available?

**Comment by erikvansebille** [comment] 2020-05-01 07:15
We've been working on a new interpolation method `linear_invdist_land_tracer` that can better handle interpolation when one of the grid cell corners is land (see PR #815). It should land in master very soon (pending review). Would that be an option for you?

Alternatively, you could use the `FieldSet.compute_on_defer` method to copy the lowest values of the velocity (at `zi-1` in your example above) to the `zi` too. See [here](https://github.com/OceanParcels/parcels/blob/master/tests/test_fieldset.py#L679-L687) for an example on how this works. 
That seems an easier approach, and also would not involve going into the parcels code itself, than creating a new interpolation method..

**Comment by miquelmassot** [comment] 2020-05-05 21:08
Hi @erikvansebille, yes, I saw it, but I also saw that it is not implemented for U and V fields, which are the ones we are using. 

Also tried with the compute_on_defer, but did not see any changes. I must be missing something. This is the compute method I passed:

``` python
def compute_nearest_currents_at_seafloor(fieldset):
    for f in [fieldset.U, fieldset.V]:
        for ti in f.loaded_time_indices:
            for xi in range(f.grid.xdim):
                for yi in range(f.grid.ydim):
                    for zi in range(f.grid.zdim - 1):
                        if f.data[ti, zi + 1, yi, xi] == 0:
                            f.data[ti, zi + 1, yi, xi] = f.data[ti, zi, yi, xi]
```
Is this more or less what you had in mind? I ran the fieldset with the argument `deferred_load=False` and it did not change the values at seafloor. Could you please let me know what am I missing?

**Comment by erikvansebille** [comment] 2020-05-08 07:17
Hi @miquelmassot. Yes, I think this might be a dask problem. @CKehl might be able to help out? Note that in the example in `test_fieldset.py`, we used dask functions to broadcast/copy:
```
    def compute(fieldset):
        # Calculating vertical weighted average
        for f in [fieldset.U, fieldset.V]:
            for tind in f.loaded_time_indices:
                data = da.sum(f.data[tind, :] * DZ, axis=0) / sum(dz)
                data = da.broadcast_to(data, (1, f.grid.zdim, f.grid.ydim, f.grid.xdim))
                f.data = f.data_concatenate(f.data, data, tind)
```
Might it be that you also need to use a specific dask function to copy data from `f.data[ti, zi, yi, xi]` into `f.data[ti, zi + 1, yi, xi]`?

Alternatively, if your input files are not too large so that they fit into memory, I think you should be able to turn off dask by setting `field_chunksize=False` when you create your `FieldSet` (right, @CKehl?)

**Comment by CKehl** [comment] 2020-05-08 10:29
Hi,
So, I don't think this has anything to do with dask. The error message is quite clear: one of your indices (ti, zi, yi or xi) is a tuple (I think it is ti - I'd need to look up the structure of `Field.loaded_time_indices` again though) - and you cannot use tuples for such multi-dimensional addressing.

If you wanna make sure it's not **dask**, Erik is right to say that you can create your fieldset with `field_chunksize=false` - then all data will be loaded in one go into the memory as numpy ndarrays.

I'll have a look on the `Field.loaded_time_indices` again in the meanwhile.

Best,
Christian

**Comment by CKehl** [comment] 2020-05-08 14:14
Hi, so: I had a look on `Field.loaded_time_indices` again, and it turns out that this variable is purely internal. It is a 3-set tuple on field creation (empty data - your case), and otherwise just a 1-entry python list with the recent relative time index (**relative**: we store 3 time steps in the cache for interpolation; depending on forward or backward simulation, the relative index is hence 0 or 2).

If you want the `ti` as intended, please just iterate over those 3 indices, so that `for ti in f.loaded_time_indices:` becomes `for ti in range(0, 3):`. 

In addition, your loop will only work if you disable dask (`field_chunksize=false`) - because with dask, `Field.data[]` does not have entries for each indices in `grid.xdim`, `grid.ydim` and `grid.zdim` (consult the topic of **lazy loading via dask** via Google).

**Comment by erikvansebille** [comment] 2020-09-01 12:35
Hi @miquelmassot. I'm now closing this Issue, but in case you are still experiencing problems, then please feel free to reopen and clarify _what_ is still not working

**Closed by erikvansebille** 2020-09-01 12:35 UTC
