### ISSUE TITLE
Reading EFDC NetCDF output into Parcels

### ISSUE THREAD

**Issue by Cyuan-hub** [OceanParcels/parcels#1360] opened 2023-05-06 13:25 UTC
Hello, I am planning to couple the hydrodynamic results simulated by EFDC to parcels. However, I found that the grids of EFDC and parcels are different. The NetCDF format of the flow field simulation output from EFDC is also different from the NetCDF format of the flow field input required by parcels.
Are there existing functions (within the codebase, or external tools) to wrangle flow data from EFDC hydrodynamic simulations into the parcels format?

**Comment by VeckoTheGecko** [comment] 2023-05-06 15:02
The [grid indexing tutorial](https://nbviewer.org/github/OceanParcels/parcels/blob/master/parcels/examples/documentation_indexing.ipynb) is a good resource to understand how grids are treated in parcels. Parcels has the capacity to handle both A grid and C grid hydrodynamics. Although I'm not familiar with the [EFDC](https://zenodo.org/record/1252355#.ZFZo4HZBw-U) model, looking online I was able to find [this manual](https://scholarworks.wm.edu/cgi/viewcontent.cgi?article=2043&context=reports) for it, which mentions on PDF page 15:

> The numerical scheme employed in EFDC to solve the equations of motion uses second order accurate spatial finite difference on a staggered or C grid.

You can use xarray to inspect the NetCDF, and then load it in using [`FieldSet.from_c_grid_dataset()`](https://docs.oceanparcels.org/en/latest/reference/fields.html?highlight=c_grid#parcels.fieldset.FieldSet.from_c_grid_dataset).

**Comment by Cyuan-hub** [comment] 2023-05-07 13:25
Thank you very much. I will study these materials diligently.

**Comment by VeckoTheGecko** [comment] 2023-05-07 17:07
Sounds good. Closing this issue for now; feel free to continue this thread if there is any additional followup.

**Closed by VeckoTheGecko** 2023-05-07 17:07 UTC

**Comment by Cyuan-hub** [comment] 2023-09-20 14:16
I hope this message finds you well. I am currently working on a simulation using Parcels and I have encountered an issue regarding particle movement.

I am using EFDC model output data in .bin format, which I have converted to NetCDF files following the format specified in the examples provided for NemoCurvilinear_data and NemoNorthSeaORCA025-N006_data.  And then I load them in using FieldSet.from_c_grid_dataset() using the variable names contained in the NetCDF. The particles are initially released within the study area.

However, when I run the simulation, the particles do not move. Instead, I receive an 'OutOfBoundsError:
OutOfBoundsError                          Traceback (most recent call last)
Cell In[4], line 35
     31 pfile = ParticleFile("2007_EFDC_data_0920_1", pset, outputdt=delta(days=1))
     33 kernels = pset.Kernel(AdvectionRK4)
---> 35 pset.execute(kernels, 
     36              runtime=delta(days=90), 
     37              dt=delta(minutes = 1), 
     38              output_file=pfile
     39             )

File ~\anaconda3\envs\py3_parcels\lib\site-packages\parcels\particleset\baseparticleset.py:548, in BaseParticleSet.execute(self, pyfunc, pyfunc_inter, endtime, runtime, dt, moviedt, recovery, output_file, movie_background_field, verbose_progress, postIterationCallbacks, callbackdt)
    546 # If we don't perform interaction, only execute the normal kernel efficiently.
    547 if self.interaction_kernel is None:
--> 548     self.kernel.execute(self, endtime=next_time, dt=dt, recovery=recovery, output_file=output_file,
    549                         execute_once=execute_once)
    550 # Interaction: interleave the interaction and non-interaction kernel for each time step.
    551 # E.g. Inter -> Normal -> Inter -> Normal if endtime-time == 2*dt
    552 else:
    553     cur_time = time

File ~\anaconda3\envs\py3_parcels\lib\site-packages\parcels\kernel\kernelsoa.py:213, in KernelSOA.execute(self, pset, endtime, dt, recovery, output_file, execute_once)
    211 recovery_kernel = recovery_map[p.state]
    212 p.set_state(StateCode.Success)
--> 213 recovery_kernel(p, self.fieldset, p.time)
    214 if p.isComputed():
    215     p.reset_state()

File ~\anaconda3\envs\py3_parcels\lib\site-packages\parcels\tools\statuscodes.py:182, in recovery_kernel_out_of_bounds(particle, fieldset, time)
    178 """Default sampling error kernel that throws OutOfBoundsError."""
    179 if particle.exception is None:
    180     # TODO: JIT does not yet provide the context that created
    181     # the exception. We need to pass that info back from C.
--> 182     raise OutOfBoundsError(particle, fieldset)
    183 else:
    184     error = particle.exception

OutOfBoundsError: 0
Particle P[1](lon=113.325000, lat=21.608600, depth=0.000000, time=0.000000)
Time: 2007-01-01T00:00:00.000000000
timestep dt: 60.0
Out-of-bounds sampling by particle at (113.325, 21.6086, 0.0)

---------------------------------------------------------------------------------------------------------------
I would like to ask for your assistance in taking a look to see if we can identify the issue. I would greatly appreciate it if you have the time. Thank you very much!

**Comment by Cyuan-hub** [comment] 2023-09-21 02:08
@VeckoTheGecko

**Comment by VeckoTheGecko** [comment] 2023-09-21 02:26
I'm out of office until Tuesday. Perhaps @erikvansebille would be able to support, otherwise I'll have to take a look at this on Tuesday 🙂

**Comment by erikvansebille** [comment] 2023-09-21 05:57
Seems that your particle is not inside your grid. What is the zonal and meridional extent of your grid? Can you follow the steps suggested by @michaeldenes in https://github.com/OceanParcels/parcels/discussions/1412#discussioncomment-6752453?

**Comment by Cyuan-hub** [comment] 2023-09-21 11:47
> I'm out of office until Tuesday. Perhaps @erikvansebille would be able to support, otherwise I'll have to take a look at this on Tuesday 🙂

Thank you for letting me know! I'll reach out to @erikvansebille for assistance. If I still need help after that, I'll be sure to get in touch with you on Tuesday. Have a great day!

**Comment by Cyuan-hub** [comment] 2023-09-26 09:51
Hi @VeckoTheGecko and @erikvansebille,  
I have tried my best to follow the advice given by yourself, but I still haven't been able to solve the problem I encountered. Can you help me figure out the reason?

The first timestep on my grid can be found here:
https://egzhueducn-my.sharepoint.com/:u:/g/personal/2111716044_e_gzhu_edu_cn/Ea_5HMYgRm9NnfUlYfhQoMwB0nInK7lErEgQsuO9915hNQ?e=BuB6eO

Here is my code:
from parcels import Field, FieldSet, ParticleSet, JITParticle, AdvectionRK4, ErrorCode, ParticleFile, Variable, ParcelsRandom
from datetime import timedelta
from glob import glob
import numpy as np
import calendar
import math
from datetime import timedelta as delta

datau_path = 'G:/JupyterNotebook/PRE_90days_EFDC_cwh/allVel_nc_0918_1/' # uv_data
ufiles = datau_path + 'EFDC_20070101U.nc'
vfiles = datau_path + 'EFDC_20070101V.nc'
filenames = {'U': ufiles, 'V': vfiles}
variables = {'U': 'uvel', 'V': 'vvel'}
dimensions = {'U': {'lat': 'nav_lat', 'lon': 'nav_lon'}, 'V': {'lat': 'nav_lat', 'lon': 'nav_lon'}, 'time': 'time_counter'}

fieldset = FieldSet.from_c_grid_dataset(filenames, variables, dimensions,  mesh='spherical', allow_time_extrapolation = True)           
 
npart = 5
lonp = 113 * np.ones(npart)
latp = [i for i in np.linspace(21.2, 21.6, npart)]

pset = ParticleSet.from_list(fieldset, JITParticle, lon=lonp, lat=latp)

pfile = ParticleFile("EFDC_2007_particles", pset, outputdt=delta(days=1))
kernels = pset.Kernel(AdvectionRK4)
pset.execute(kernels, runtime=delta(days=50), dt=delta(hours=6), output_file=pfile)

and I get this error message:
______________________________________________________________________________________________
OutOfBoundsError                          Traceback (most recent call last)
Cell In[7], line 3
      1 pfile = ParticleFile("EFDC_2007_particles.zarr", pset, outputdt=delta(days=1))
      2 kernels = pset.Kernel(AdvectionRK4)
----> 3 pset.execute(kernels, runtime=delta(days=50), dt=delta(hours=6), output_file=pfile)

File ~\anaconda3\envs\py3_parcels\lib\site-packages\parcels\particleset\baseparticleset.py:548, in BaseParticleSet.execute(self, pyfunc, pyfunc_inter, endtime, runtime, dt, moviedt, recovery, output_file, movie_background_field, verbose_progress, postIterationCallbacks, callbackdt)
    546 # If we don't perform interaction, only execute the normal kernel efficiently.
    547 if self.interaction_kernel is None:
--> 548     self.kernel.execute(self, endtime=next_time, dt=dt, recovery=recovery, output_file=output_file,
    549                         execute_once=execute_once)
    550 # Interaction: interleave the interaction and non-interaction kernel for each time step.
    551 # E.g. Inter -> Normal -> Inter -> Normal if endtime-time == 2*dt
    552 else:
    553     cur_time = time

File ~\anaconda3\envs\py3_parcels\lib\site-packages\parcels\kernel\kernelsoa.py:213, in KernelSOA.execute(self, pset, endtime, dt, recovery, output_file, execute_once)
    211 recovery_kernel = recovery_map[p.state]
    212 p.set_state(StateCode.Success)
--> 213 recovery_kernel(p, self.fieldset, p.time)
    214 if p.isComputed():
    215     p.reset_state()

File ~\anaconda3\envs\py3_parcels\lib\site-packages\parcels\tools\statuscodes.py:182, in recovery_kernel_out_of_bounds(particle, fieldset, time)
    178 """Default sampling error kernel that throws OutOfBoundsError."""
    179 if particle.exception is None:
    180     # TODO: JIT does not yet provide the context that created
    181     # the exception. We need to pass that info back from C.
--> 182     raise OutOfBoundsError(particle, fieldset)
    183 else:
    184     error = particle.exception

OutOfBoundsError: 0
Particle P[0](lon=113.000000, lat=21.200000, depth=0.000000, time=0.000000)
Time: 0.0
timestep dt: 21600.0
Out-of-bounds sampling by particle at (113.0, 21.2, 0.0)
_____________________________________________________________________________________
When "print(np.min(fieldset.U.lon), np.max(fieldset.U.lon), np.min(fieldset.U.lat), np.max(fieldset.U.lat))", it produces:
(112.825, 115.517, 21.0769, 22.3334)

When "pset.show(field = fieldset.U)",  it produces:
![image](https://github.com/OceanParcels/parcels/assets/104747402/3898fccb-cd95-4c3f-816e-b37b2d4ccd69)

**Comment by erikvansebille** [comment] 2023-09-28 06:20
Dear @Cyuan-hub, I think I found the issue. The problem is that your longitude grid is not monotonically increasing. For example, if I do this
```python
plt.plot(np.gradient(fieldset.U.grid.lat[:,0]))
plt.xlabel('longitude index')
plt.ylabel('longitude value gradient (degrees)')
plt.show()
```
I get the figure below
![image](https://github.com/OceanParcels/parcels/assets/14315062/225964e9-526c-457e-a189-f4c8d1d30a1a)

So there are points (close to the west-most part of the domain) where the gradient in longitude values is negative. Parcels then has troubles finding the correct cell that your particle is in.

I don't know where this hydrodynamic data comes from, but your grid is not 'smooth' enough for Parcels to work...

**Comment by Cyuan-hub** [comment] 2023-09-29 14:53
Dear @erikvansebille,

Thank you so much for taking the time to look into this and providing valuable insights.  Your observation regarding the non-monotonically increasing longitude grid is incredibly helpful.  I'll investigate the data source to see if we can make the necessary adjustments for Parcels to function smoothly.

Your expertise is greatly appreciated!

Best regards,

Cyuan-hub

**Comment by Cyuan-hub** [comment] 2023-10-07 13:14
> Dear @Cyuan-hub, I think I found the issue. The problem is that your longitude grid is not monotonically increasing. For example, if I do this
> 
> ```python
> plt.plot(np.gradient(fieldset.U.grid.lat[:,0]))
> plt.xlabel('longitude index')
> plt.ylabel('longitude value gradient (degrees)')
> plt.show()
> ```
> 
> I get the figure below ![image](https://user-images.githubusercontent.com/14315062/271190488-225964e9-526c-457e-a189-f4c8d1d30a1a.png)
> 
> So there are points (close to the west-most part of the domain) where the gradient in longitude values is negative. Parcels then has troubles finding the correct cell that your particle is in.
> 
> I don't know where this hydrodynamic data comes from, but your grid is not 'smooth' enough for Parcels to work...



> Dear @Cyuan-hub, I think I found the issue. The problem is that your longitude grid is not monotonically increasing. For example, if I do this
> 
> ```python
> plt.plot(np.gradient(fieldset.U.grid.lat[:,0]))
> plt.xlabel('longitude index')
> plt.ylabel('longitude value gradient (degrees)')
> plt.show()
> ```
> 
> I get the figure below ![image](https://user-images.githubusercontent.com/14315062/271190488-225964e9-526c-457e-a189-f4c8d1d30a1a.png)
> 
> So there are points (close to the west-most part of the domain) where the gradient in longitude values is negative. Parcels then has troubles finding the correct cell that your particle is in.
> 
> I don't know where this hydrodynamic data comes from, but your grid is not 'smooth' enough for Parcels to work...

Hi @erikvansebille,
Regarding your mention of potential difficulties with Parcels in this specific scenario, I am very interested and would like to know if you have plans to enhance Parcels to make it compatible with such data? 

Additionally, if I wish to continue using Parcels in the current situation, do you have any advice or guidance that could help me address this issue?

Looking forward to your suggestions and guidance.

Best regards,

Cyuan-hub

**Comment by Cyuan-hub** [comment] 2023-10-07 13:15
Hi @erikvansebille,
Regarding your mention of potential difficulties with Parcels in this specific scenario, I am very interested and would like to know if you have plans to enhance Parcels to make it compatible with such data?

Additionally, if I wish to continue using Parcels in the current situation, do you have any advice or guidance that could help me address this issue?

Looking forward to your suggestions and guidance.

Best regards,

Cyuan-hub

**Comment by erikvansebille** [comment] 2023-10-09 11:58
No, this will not be supported anytime soon in Parcels, I'm afraid. You could consider regrinding/interpolating the grid, although that comes with its own problems (see the [stuck particles](https://docs.oceanparcels.org/en/latest/examples/documentation_stuck_particles.html) tutorial)

**Comment by Cyuan-hub** [comment] 2023-10-09 12:37
> No, this will not be supported anytime soon in Parcels, I'm afraid. You could consider regrinding/interpolating the grid, although that comes with its own problems (see the [stuck particles](https://docs.oceanparcels.org/en/latest/examples/documentation_stuck_particles.html) tutorial)

Hi, @erikvansebille, 
Thank you for your prompt response and for providing clarity on the current capabilities of Parcels in this context. While it's disheartening to hear that the desired functionality won't be supported in the near future, I truly appreciate your candor.

I will certainly explore the option of regrinding/interpolating the grid, although I understand that this may present its own set of challenges.

Your guidance is invaluable, and I'm grateful for your expertise in this matter. If there are any updates or developments in the future, I would be eager to learn about them.

Thank you once again for your time and assistance.

Best regards,

Cyuan-hub

**Comment by Cyuan-hub** [comment] 2023-10-10 01:48
Hi, @erikvansebille,
I took another look at the [Documentation and Tutorials] (https://docs.oceanparcels.org/en/latest/documentation.html) and it explicitly states support for any curvilinear grid, in other word, it should support curvilinear orthogonal grids. Here are some screenshots for reference:
![Fig 1](https://github.com/OceanParcels/parcels/assets/104747402/238b8be3-9a7f-4bf9-9bb2-63dd8aba9a37)
![Fig 2](https://github.com/OceanParcels/parcels/assets/104747402/ca63916c-7730-49c7-9166-ac5bc6d7853f)
Given this, I'm puzzled by the current statement that it's not supported. Could there be an error in the manual? This has left me quite confused.

Looking forward to your professional insights into this matter.

Best regards,

Cyuan-hub

**Comment by Cyuan-hub** [comment] 2023-10-10 01:50
> No, this will not be supported anytime soon in Parcels, I'm afraid. You could consider regrinding/interpolating the grid, although that comes with its own problems (see the [stuck particles](https://docs.oceanparcels.org/en/latest/examples/documentation_stuck_particles.html) tutorial)

Hi, @erikvansebille,
I took another look at the [Documentation and Tutorials](https://docs.oceanparcels.org/en/latest/documentation.html) and it explicitly states support for any curvilinear grid, in other word, it should support curvilinear orthogonal grids. Here are some screenshots for reference:
![Fig 1](https://github.com/OceanParcels/parcels/assets/104747402/968e1d08-68de-4e3b-809e-1d7843e54abe)
![Fig 2](https://github.com/OceanParcels/parcels/assets/104747402/5f00f265-3c37-4ca4-be53-644a115a987d)

Given this, I'm puzzled by the current statement that it's not supported. Could there be an error in the manual? This has left me quite confused.

Looking forward to your professional insights into this matter.

Best regards,

Cyuan-hub
