### ISSUE TITLE
Using from_netcdf getting a TypeError

### ISSUE THREAD

**Issue by michaeldenes** [OceanParcels/parcels#425] opened 2018-08-27 11:41 UTC
Hi all,
I'm fairly new to this, so it could be just user error. I'm using model output from a mom01v5 model, and trying to use the FieldSet.from_netcdf method to create a fieldset, but I'm getting the error
`TypeError: '>' not supported between instances of 'datetime.timedelta' and 'int'`

My code:
`filenames = "/g/data3/hh5/tmp/cosima/mom01v5/KDS75/output*/ocean__*_*.nc"`
`variables = {'U': 'u',
             'V': 'v'}`
`dimensions = {'lat': 'geolat_c',
              'lon': 'geolon_c',
              'time': 'time',
              'depth': 'st_ocean'}`
`fieldset = FieldSet.from_netcdf(filenames, variables, dimensions)`

The issue appears to be in parcels/field.py line 310
`assert(np.all((time[1:]-time[:-1]) > 0))`
when called from parcels/fieldset.py line 201-203
`fields[var] = Field.from_netcdf(paths, var, dims, inds, grid=grid, mesh=mesh, allow_time_extrapolation=allow_time_extrapolation, time_periodic=time_periodic, full_load=full_load, **kwargs)`

Any help would be great! Thanks.

**Comment by erikvansebille** [comment] 2018-08-27 11:50
Hi Michael,

Thanks for reporting this Issue; it appears to be a bug yes. For some reason, your `time` is a `datetime`, rather than a float, as `Field.from_netcdf` is always supposed to return a float. Not really sure how that could happen..

Would you be able to share one of your output files with me? Then it will be easier for me to debug and provide a fix

**Comment by michaeldenes** [comment] 2018-08-27 12:03
Hi Erik, thanks for getting back so quickly. Unfortunately the files are rather large (~5.6GB each). Are there any diagnostics I could run which would help?

**Comment by erikvansebille** [comment] 2018-08-27 12:06
Can't you share one file over e.g. wetransfer with me? I'm at e.vansebille@uu.nl. That really is easier (and faster!) than trying to debug over this Issue tracker

**Comment by erikvansebille** [comment] 2018-08-27 12:30
Whatever you can send is useful. But make sure it has the correct
dimensions (including `time`) as the problem seems to be in reading that
dimension

**Comment by erikvansebille** [comment] 2018-08-27 13:31
Hi Michael,

The good news is that I downloaded your files and could reproduce the bug. I also know now that the issue is with the `time:calendar_type = "NOLEAP"` attribute in your netcdf file.

I'll dig a little deeper in how we could support these NOLEAP calendars in Parcels. The issue is that they don't get converted to `numpy.datetime64` objects, as is expected by Parcels. More soon!

**Comment by michaeldenes** [comment] 2018-08-27 13:35
Thanks Erik, I really appreciate this! I've not had much experience with ocean model output or netcdf files before, so thank you!

**Comment by erikvansebille** [comment] 2018-08-27 13:55
I've created a new branch at https://github.com/OceanParcels/parcels/tree/cftime_noleap_calendar that is a quick and dirty implementation of `cftme._cftimeDatetimeNoLeap` calendars. Could you check if you can run Parcels using this branch? Perhaps you may need to `pip install cftime` too

**Comment by michaeldenes** [comment] 2018-08-28 01:30
Hi Erik, I believe it's a related issue, so I won't open a new one.
When I create a particle set
`pset = ParticleSet.from_line(fieldset=fieldset, size=10, pclass=JITParticle, start=(31, -31), finish=(38, -38))`
and try to plot the particles with the U field
`pset.show(field=fieldset.U)`
I get the type error:
`TypeError: cannot compare cftime.DatetimeNoLeap(96, 1, 3, 12, 0, 0, 0, 2, 3) and 0.0`
The issue looks to come down to line 965 in parcels/field.py
`ti = (time_data <= g.time[tindex]).argmin() - 1`

Similarly, if I try to advect those particles with
`pset.execute(AdvectionRK4, runtime=timedelta(days=20), dt=timedelta(days=1))`
I get the same error
`TypeError: cannot compare cftime.DatetimeNoLeap(96, 1, 3, 12, 0, 0, 0, 2, 3) and 0.0`
Same line (965 in parcels/field.py) throws this error.

**Comment by michaeldenes** [comment] 2018-08-28 07:48
Hi Erik, thanks for this, I've rerun with your suggestion for the ocean only area. I could get the particles to show using `pset.show()`, and advect using `pset.execute`.
However, I couldn't get `pset.show(field=fieldset.U)` working for example, but I think that's down to user error! I'll likely read through the code itself to understand what's going on and how I can use the show() function. Thank you again!

**Comment by michaeldenes** [comment] 2018-08-31 04:06
Hi Erik, when using the `output_file` argument in pset.execute, it throws the same type error
`TypeError: cannot compare cftime.DatetimeNoLeap(96, 1, 3, 12, 0, 0, 0, 2, 3) and 0`
Issue on line 68 of parcels/particlefile.py 

My code for reference:
`output_file = pset.ParticleFile(name="test_single_particle", outputdt=timedelta(hours=12))
pset.execute(AdvectionRK4, runtime=timedelta(days=20), dt=timedelta(days=1), output_file=output_file)`

**Comment by erikvansebille** [comment] 2018-08-31 08:51
I've just updated the https://github.com/OceanParcels/parcels/tree/cftime_noleap_calendar branch to also be compatible with NOLEAP calendars in ParticleFile writing. Let me know if this works

**Comment by michaeldenes** [comment] 2018-09-03 12:34
Hi Erik, apologies for the delay. It looks to have worked, I just need to think about the land set to NaN problem now! I'll play around with some more functions to see if the issue pops up elsewhere, but thank you for all your help so far!

**Comment by michaeldenes** [comment] 2018-09-09 12:33
Hi Erik,
One thing I have noticed is that once a particle goes out of bounds, there is a type error:
`TypeError: ufunc add cannot use operands with types dtype('O') and dtype('<m8[s]')`
caused on line 33 of parcels/kernels/error.py
`time = fieldset.time_origin + np.timedelta64(int(time), 's')`
Would this be caused by the `time` type as well?

**Comment by erikvansebille** [comment] 2018-09-25 17:53
Hi Michael, I was wondering if you've had a try of the new code in PR #456. Does it work for you?  If so, we can merge the PR and close this Issue

**Comment by erikvansebille** [comment] 2018-09-28 06:51
Fixed in #456

**Closed by erikvansebille** 2018-09-28 06:51 UTC
